name: Build CV PDFs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile LaTeX documents
      uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          cv-en.tex
          cv-es.tex
          cv-pt.tex
        args: -pdf -interaction=nonstopmode -file-line-error

    - name: "[EN] Upload CV"
      uses: actions/upload-artifact@v4
      with:
        name: cv-en
        path: cv-en.pdf

    - name: "[ES] Upload CV"
      uses: actions/upload-artifact@v4
      with:
        name: cv-sp
        path: cv-es.pdf

    - name: "[PT] Upload CV"
      uses: actions/upload-artifact@v4
      with:
        name: cv-pt
        path: cv-pt.pdf

    - name: Create Release on Tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cv-en.pdf
          cv-es.pdf
          cv-pt.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
